# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 186c828b1f18f2f78174a953d005fd632a2cda82d2757f0701bdb5fd456f65ffa3c9e8f70df82a4b3b6f72cb135bc3a71375859239996c58b4e663dd70c4e90d

test:
  secret_key_base: c67165ee0253e888aa265d0393bcb8d2bd757cf37e06f6bb37a438ae793d9dcdb23994e04ca05adf41f8f86a56ed525e4e997a2af55f3e8c5aa8b2a755ced5f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["MEXGUA_KEY_BASE"] %>
  usrs: etenorio,lruiz,tochoa,maguilera,castillo,ganunez
  usr: adminweb
  usr2: Erik
